# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  create-infastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create instance"
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name my-stack
workflows:
  my-workflow:
    jobs:
      - create-infastructure
