---
- name: "update package"
  become: yes
  apt:
    update_cache: yes

- name: "upgrage package"
  become: yes
  apt:
    upgrade: yes

- name: "remove lib"
  become: yes
  apt:
    autoremove: yes

- name: "install node"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  apt:
    name: pm2
    state: present
    global: yes
    production: yes

- name: "create dir"
  file:
    path: ~/web
    state: directory

- name: "copy index"
  template: 
    src: files/index.js
    dest: ~/web/index.js

- name: Execute node
  shell: |
    pm2 start ~/web/index.js -f

